on:
  push:
    branches:
      - master
jobs:
  push_changes:
    name: "Push Changes"
    runs-on: ubuntu-18.04
    steps:
      - name: Pull existing image
        run: docker pull sittingonthedock/vscode-dotnet-essentials:3.0 || true
      - name: Checkout
        uses: actions/checkout@master
      - name: Build new image
        run: |
          docker login -u {{ secrets.DockerHubUser }} -p {{ secrets.DockerHubPassword }}
          docker build -t sittingonthedock/vscode-dotnet-essentials:3.0 vscode-dotnet-essentials/3.0
    container:
      image: sittingonthedock/build-docker:1.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock