on: push

jobs:
  push_container_updates:
    name: "Push Changes to ${{ matrix.image.name }}:${{ matrix.image.tag }}"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image ${{ matrix.image.name }}:${{ matrix.image.tag }}
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/${{ matrix.image.name }}:${{ matrix.image.tag }}
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: ${{ matrix.image.name }}/${{ matrix.image.tag }}/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
    strategy:
      matrix:
        image:
          - name: zsh-shell
            tag: bionic
          - name: aws-tools
            tag: bionic
          - name: build-docker
            tag: 1.0
          - name: vscode-dotnet-essentials
            tag: 2.1
          - name: vscode-dotnet-essentials
            tag: 3.1
          - name: vscode-dotnet-essentials
            tag: lambda
          - name: vscode-dotnet-essentials
            tag: ecs
          - name: vscode-node-essentials
            tag: 12
          - name: vscode-node-essentials
            tag: actions-js
          - name: vscode-node-essentials
            tag: actions-ts
