on:
  push:
    branches:
      - master
jobs:
  push_changes:
    name: "Push Changes"
    runs-on: ubuntu-18.04
    steps:
      - name: Pull existing image
        run: |
          docker pull sittingonthedock/vscode-dotnet-essentials:3.0
    container:
      image: sittingonthedock/build-docker:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock