on:
  push:
    branches:
      - master
jobs:
  push_changes:
    name: "Push Changes"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/
      - name: Pull existing image
        run: docker pull ${{ secrets.DockerHubUser }}/vscode-dotnet-essentials:3.0 || true
      - name: Checkout
        uses: actions/checkout@master
      - name: Build new image
        run: |
          docker build -t ${{ secrets.DockerHubUser }}/vscode-dotnet-essentials:3.0 \
            --cache-from ${{ secrets.DockerHubUser }}/vscode-dotnet-essentials:3.0 \
            -f vscode-dotnet-essentials/3.0/Dockerfile
      - name: Push built image to DockerHub
        run: |
          docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubPassword }}
          docker push ${{ secrets.DockerHubUser }}/vscode-dotnet-essentials:3.0
    container:
      image: sittingonthedock/build-docker:1.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock