on: push

jobs:
  push_container_updates:
    name: "Push Changes to ${{ matrix.image.name }}:${{ matrix.image.tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image ${{ matrix.image.name }}:${{ matrix.image.tag }}
        uses: docker/build-push-action@v1
        with:
          repository: sittingonthedock/${{ matrix.image.name }}
          tags: ${{ matrix.image.tag }}
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          path: ${{ matrix.image.name }}/${{ matrix.image.tag }}
    strategy:
      matrix:
        image:
          - name: "zsh-shell"
            tag: "bionic"
          - name: "aws-tools"
            tag: "bionic"
          - name: "build-docker"
            tag: "1.0"
          - name: "vscode-dotnet-essentials"
            tag: "2.1"
          - name: "vscode-dotnet-essentials"
            tag: "3.1"
          - name: "vscode-dotnet-essentials"
            tag: "lambda"
          - name: "vscode-dotnet-essentials"
            tag: "ecs"
          - name: "vscode-node-essentials"
            tag: "12"
          - name: "vscode-node-essentials"
            tag: "actions-js"
          - name: "vscode-node-essentials"
            tag: "actions-ts"
