on: push

jobs:
  push_zsh_shell_bionic:
    name: "Push Changes to zsh-shell:bionic"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image zsh-shell:bionic
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/zsh-shell:bionic
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: zsh-shell/bionic/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_aws_tools_bionic:
    name: "Push Changes to aws-tools:bionic"
    runs-on: ubuntu-18.04
    needs: push_zsh_shell_bionic
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image aws-tools:bionic
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/aws-tools:bionic
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: aws-tools/bionic/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_build_docker_1_0:
    name: "Push Changes to build-docker:1.0"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image build-docker:1.0
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/build-docker:1.0
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: build-docker/1.0/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_dotnet_2_1:
    name: "Push Changes to vscode-dotnet-essentials:2.1"
    runs-on: ubuntu-18.04
    needs: push_aws_tools_bionic
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image vscode-dotnet-essentials:2.1
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:2.1
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/2.1/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_dotnet_3_1:
    name: "Push Changes to vscode-dotnet-essentials:3.1"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image vscode-dotnet-essentials:3.1
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:3.1
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/3.1/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_dotnet_lambda:
    name: "Push Changes to vscode-dotnet-essentials:lambda"
    runs-on: ubuntu-18.04
    needs: push_dotnet_2_1
    steps:
      - name: Checkout
        uses: actions/checkout@master 
      - name: Publish Image vscode-dotnet-essentials:lambda
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:lambda
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/lambda/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_dotnet_ecs:
    name: "Push Changes to vscode-dotnet-essentials:ecs"
    runs-on: ubuntu-18.04
    needs: push_dotnet_3_1
    steps:
      - name: Checkout
        uses: actions/checkout@master 
      - name: Publish Image vscode-dotnet-essentials:ecs
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:ecs
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/ecs/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_node_12:
    name: "Push Changes to vscode-node-essentials:12"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image vscode-node-essentials:12
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-node-essentials:12
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-node-essentials/12/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_node_actions_js:
    name: "Push Changes to vscode-node-essentials:actions-js"
    runs-on: ubuntu-18.04
    needs: push_node_12
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image vscode-node-essentials:actions-js
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-node-essentials:actions-js
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-node-essentials/actions-js/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_node_actions_ts:
    name: "Push Changes to vscode-node-essentials:actions-ts"
    runs-on: ubuntu-18.04
    needs: push_node_12
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image vscode-node-essentials:actions-ts
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-node-essentials:actions-ts
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-node-essentials/actions-ts/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
