on: push

jobs:
  push_changes:
    name: "Push Changes"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Publish Image 
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:2.1
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/2.1/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
    container:
      image: sittingonthedock/build-docker:1.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock