on: push

jobs:
  push_dotnet_2_1:
    name: "Push Changes to vscode-dotnet-essentials:2.1"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master            
      - name: Publish Image vscode-dotnet-essentials:2.1
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:2.1
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/2.1/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_dotnet_3_0:
    name: "Push Changes to vscode-dotnet-essentials:2.1"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master            
      - name: Publish Image vscode-dotnet-essentials:3.0
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:3.0
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/3.0/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_dotnet_lambda:
    name: "Push Changes to vscode-dotnet-essentials:lambda"
    runs-on: ubuntu-18.04
    needs: push_dotnet_2_1
    steps:
      - name: Checkout
        uses: actions/checkout@master            
      - name: Publish Image vscode-dotnet-essentials:lambda
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-dotnet-essentials:lambda
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-dotnet-essentials/lambda/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
  push_node_12:
    name: "Push Changes to vscode-dotnet-essentials:lambda"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master            
      - name: Publish Image vscode-node-essentials:12
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sittingonthedock/vscode-node-essentials:12
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubPassword }}
          dockerfile: vscode-node-essentials/12/Dockerfile
          cache: ${{ github.event_name != 'schedule' }}
    container:
      image: sittingonthedock/build-docker:1.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock